name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'  # Ensures submodules are checked out

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev
        
        # Install cppcheck from snap or directly download the latest version if necessary
        sudo snap install cppcheck --classic

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Test
      working-directory: build
      run: |
        ctest --output-on-failure

    - name: Run linter on specified directories
      run: |
        cppcheck --enable=all --error-exitcode=1 src/ include/
