name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev
        sudo apt-get install -y cppcheck
        sudo apt-get install -y google-mock
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest/googletest
        sudo cmake .
        sudo cmake --build . --target install

    - name: Run linter
      run: |
        cppcheck --enable=all --error-exitcode=1 .

    - name: Build
      run: |
        g++ -o main main.cpp -lglfw -ldl -pthread
        g++ -o test_main test_main.cpp -lgtest -lpthread

    - name: Run unit tests
      run: |
        ./test_main
