name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'  # Ensures submodules are checked out

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev
        
        # Remove the existing cppcheck from the package manager if it's outdated
        sudo apt-get remove --auto-remove cppcheck

        # Install cppcheck from snap which provides the latest version
        sudo snap install cppcheck --classic

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Test
      working-directory: build
      run: |
        ctest --output-on-failure

    - name: Run linter
      run: |
        # Run cppcheck with exclude option to avoid checking external libraries
        cppcheck --enable=all --error-exitcode=1 --exclude=external .
